In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
heart_Data= pd.read_csv('/content/heart_disease_data.csv')

In [3]:
heart_Data.head()

   age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1        0      150      0      2.3      0   0     1       1
1   37    1   2       130   250    0        1      187      0      3.5      0   0     2       1
2   41    0   1       130   204    0        0      172      0      1.4      2   0     2       1
3   56    1   1       120   236    0        1      178      0      0.8      2   0     2       1
4   57    0   0       120   354    0        1      163      1      0.6      2   0     2       1

In [4]:
heart_Data.tail()

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  ca  thal  target
298   57    0   0       140   241    0        1      123      1      0.2      1   0     3       0
299   45    1   3       110   264    0        1      132      0      1.2      1   0     3       0
300   68    1   0       144   193    1        1      141      0      3.4      1   2     3       0
301   57    1   0       130   131    0        1      115      1      1.2      1   1     3       0
302   57    0   1       130   236    0        0      174      0      0.0      1   1     2       0

In [5]:
#no of rows and columns in the datasete
heart_Data.shape

(303, 14)

In [7]:
#Basic info about the data
heart_Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [8]:
#Checking for missing values
heart_Data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [9]:
#Statistical measures about the data
heart_Data.describe()

              age         sex          cp  ...          ca        thal      target
count  303.000000  303.000000  303.000000  ...  303.000000  303.000000  303.000000
mean    54.366337    0.683168    0.966997  ...    0.729373    2.313531    0.544554
std      9.082101    0.466011    1.032052  ...    1.022606    0.612277    0.498835
min     29.000000    0.000000    0.000000  ...    0.000000    0.000000    0.000000
25%     47.500000    0.000000    0.000000  ...    0.000000    2.000000    0.000000
50%     55.000000    1.000000    1.000000  ...    0.000000    2.000000    1.000000
75%     61.000000    1.000000    2.000000  ...    1.000000    3.000000    1.000000
max     77.000000    1.000000    3.000000  ...    4.000000    3.000000    1.000000

[8 rows x 14 columns]

In [10]:
#Checking the distribution of target variable
heart_Data['target'].value_counts()

target
1    165
0    138
Name: count, dtype: int64

*1 --> Defective Heart*<Br>
*2 --> Healthy Heart*

In [11]:
#Splitting features and target

x=heart_Data.drop(columns='target',axis=1)
y=heart_Data['target']

In [12]:
print(x)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  ca  thal
0     63    1   3       145   233    1        0      150      0      2.3      0   0     1
1     37    1   2       130   250    0        1      187      0      3.5      0   0     2
2     41    0   1       130   204    0        0      172      0      1.4      2   0     2
3     56    1   1       120   236    0        1      178      0      0.8      2   0     2
4     57    0   0       120   354    0        1      163      1      0.6      2   0     2
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...    ...  ..   ...
298   57    0   0       140   241    0        1      123      1      0.2      1   0     3
299   45    1   3       110   264    0        1      132      0      1.2      1   0     3
300   68    1   0       144   193    1        1      141      0      3.4      1   2     3
301   57    1   0       130   131    0        1      115      1      1.2      1   1     3
302   57    0   1       130   236    0        0      174      0      0.0      1   1     2

[303 rows x 13 columns]

In [13]:
print(y)

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [15]:
#Splitting into Test,Development and Test data
x_temp, x_test, y_temp, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

#Now we have to split between Training vs Development
x_train,x_dev,y_train,y_dev= train_test_split(x_temp, y_temp, test_size=0.2, random_state=42)
print('Training set size: ',x_train.shape)
print('Development set size: ',x_dev.shape)
print('Test set size: ',x_test.shape)

Training set size:  (193, 13)
Development set size:  (49, 13)
Test set size:  (61, 13)

In [17]:
# Model Training for Logistic Regression
log = LogisticRegression()
log.fit(x_train, y_train)
#Predict on thr development set
y_dev_pred= log.predict(x_dev)
print('Accuracy: ',accuracy_score(y_dev,y_dev_pred))

Accuracy:  0.7959183673469388

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [18]:
#Predict and evaluate the Test set
y_test_pred=log.predict(x_test)
print('Accuracy on the test set: ',accuracy_score(y_test,y_test_pred))

Accuracy on the test set:  0.8524590163934426

*Building a predictive data*

In [19]:
input_Data=(56,1,1,120,236,0,1,178,0,0.8,2,0,2)

#Change the input data to numpy array
input_data_numpy_array= np.asarray(input_Data)

#Reshape the numpy array as we are predicting for only one instance
input_data_reshape=input_data_numpy_array.reshape(1,-1)

prediction= log.predict(input_data_reshape)
print(prediction)
if(prediction[0]==0):
  print('Person doesnot have a heart disease')
else:
  print('Person have a heart disease')

[1]
Person have a heart disease

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(